# Generated by Django 3.2.25 on 2025-08-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20250825_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='likes',
        ),
    ]
